import * as art from '../art'
import { dots, fish, jacket, jelly, pool } from '../draw'
import { sea, type Collectible } from './build'

/** The sea's twenty-six finds, line A then line B. */
export const SEA: readonly Collectible[] = [
  // SEA, line A
  sea(
    'a',
    3,
    'sea-a-plankton',
    'plankton glow',
    'a few cyan dots, drifting',
    0.15,
    0.641,
    50,
    'drift',
    () =>
      dots(
        [
          [20, 30, 2],
          [40, 55, 1.6],
          [62, 25, 2.4],
          [75, 60, 1.4],
          [50, 80, 2],
          [30, 70, 1.2],
        ],
        'var(--glow)',
      ),
  ),
  sea('a', 7, 'sea-a-fish', 'a fish', 'the first company', 0.3, 0.666, 32, 'swim', () =>
    fish(50, 50, 50, 'var(--teal)'),
  ),
  sea(
    'a',
    14,
    'sea-a-school',
    'a school of fish',
    'six, turning together',
    0.55,
    0.649,
    70,
    'swim',
    () =>
      [
        [20, 30],
        [45, 22],
        [70, 32],
        [30, 55],
        [55, 50],
        [80, 60],
      ]
        .map(([x, y]) => fish(x ?? 0, y ?? 0, 20, 'var(--glow)'))
        .join(''),
  ),
  sea(
    'a',
    21,
    'sea-a-anchor',
    'an anchor',
    'half buried; somebody stayed',
    0.1,
    0.68,
    28,
    'none',
    art.anchor,
  ),
  sea(
    'a',
    30,
    'sea-a-jelly',
    'a jellyfish at night',
    'only out after dark',
    0.8,
    0.666,
    36,
    'drift',
    () => jelly(50, 40, 50, 'var(--glow)'),
    true,
  ),
  sea(
    'a',
    45,
    'sea-a-dolphin',
    'a dolphin',
    'jumps when you tap',
    0.62,
    0.629,
    56,
    'swim',
    art.dolphin,
  ),
  sea(
    'a',
    60,
    'sea-a-lighthouse',
    'a lighthouse',
    'a beam over the water',
    0.92,
    0.55,
    40,
    'sweep',
    art.lighthouse,
  ),
  sea(
    'a',
    90,
    'sea-a-jacket',
    'the red jacket',
    'the whale wears it now',
    0.45,
    0.678,
    36,
    'none',
    () => jacket(50, 40, 50),
  ),
  sea(
    'a',
    120,
    'sea-a-calf',
    'a whale calf',
    'follows the whale',
    0.38,
    0.633,
    40,
    'swim',
    art.calf,
  ),
  sea(
    'a',
    180,
    'sea-a-song',
    'the whale sings',
    'a pulse of light across the sea',
    0.5,
    0.657,
    160,
    'twinkle',
    () =>
      [20, 35, 50]
        .map(
          (r) =>
            `<circle cx="50" cy="50" r="${r}" stroke="var(--glow)" stroke-width="1" fill="none" opacity="${0.6 - r / 100}"/>`,
        )
        .join(''),
  ),
  // SEA, line B
  sea(
    'b',
    3,
    'sea-b-pool',
    'a tide pool',
    'a ring of light at the water line',
    0.84,
    0.6,
    44,
    'twinkle',
    () =>
      dots(
        [
          [15, 50, 2],
          [30, 38, 1.5],
          [50, 34, 2],
          [70, 38, 1.5],
          [85, 50, 2],
          [70, 62, 1.5],
          [50, 66, 2],
          [30, 62, 1.5],
        ],
        'var(--glow)',
      ),
  ),
  sea(
    'b',
    7,
    'sea-b-seahorse',
    'a seahorse',
    'holding on to a weed',
    0.72,
    0.68,
    28,
    'sway',
    art.seahorse,
  ),
  sea('b', 14, 'sea-b-crab', 'a crab', 'walking the floor', 0.25, 0.682, 28, 'sway', art.crab),
  sea(
    'b',
    21,
    'sea-b-turtle',
    'a sea turtle',
    'drifting past, slowly',
    0.42,
    0.649,
    44,
    'swim',
    art.turtle,
  ),
  sea(
    'b',
    30,
    'sea-b-jellies',
    'a pair of jellyfish',
    'two, after dark',
    0.14,
    0.666,
    48,
    'drift',
    () => `${jelly(30, 40, 34, 'var(--star)')}${jelly(68, 55, 28, 'var(--glow)')}`,
    true,
  ),
  sea(
    'b',
    45,
    'sea-b-manta',
    'a manta ray',
    'gliding under everything',
    0.65,
    0.68,
    90,
    'swim',
    art.manta,
  ),
  sea(
    'b',
    60,
    'sea-b-octopus',
    'an octopus',
    'in a cave at the bottom',
    0.9,
    0.682,
    40,
    'sway',
    art.octopus,
  ),
  sea(
    'b',
    90,
    'sea-b-ship',
    'a sunken ship',
    'with its own glow',
    0.3,
    0.684,
    70,
    'none',
    art.ship,
  ),
  sea(
    'b',
    120,
    'sea-b-narwhal',
    'a narwhal',
    'because why not',
    0.2,
    0.633,
    52,
    'swim',
    art.narwhal,
  ),
  sea(
    'b',
    180,
    'sea-b-deep',
    'the deep opens',
    'a second layer, with its own lights',
    0.5,
    0.686,
    200,
    'twinkle',
    () => {
      // A darkness with no rim: the deep opens under the sea, its own lights in it.
      const [shade, fill] = pool('#010205', 0.85)
      return `${shade}<ellipse cx="50" cy="66" rx="50" ry="34" fill="${fill}"/>${dots(
        [
          [10, 70, 1.5],
          [25, 85, 1],
          [40, 60, 2],
          [60, 90, 1.5],
          [75, 65, 1],
          [90, 80, 2],
        ],
        'var(--jacket)',
      )}`
    },
  ),
  // The first year's end, line A and line B.
  sea(
    'a',
    240,
    'sea-a-otter',
    'a sea otter',
    'afloat, holding a shell',
    0.6,
    0.64,
    48,
    'sway',
    art.otter,
  ),
  sea('a', 300, 'sea-a-seal', 'a seal', 'asleep on its rock', 0.2, 0.67, 46, 'none', art.seal),
  sea(
    'a',
    365,
    'sea-a-pod',
    'a pod of whales',
    'a year of showing up',
    0.5,
    0.65,
    72,
    'swim',
    art.pod,
  ),
  sea(
    'b',
    240,
    'sea-b-puffer',
    'a pufferfish',
    'round when surprised',
    0.75,
    0.66,
    34,
    'drift',
    art.puffer,
  ),
  sea(
    'b',
    300,
    'sea-b-coral',
    'a coral',
    'a little taller every year',
    0.35,
    0.68,
    40,
    'none',
    art.coral,
  ),
  sea('b', 365, 'sea-b-orca', 'an orca', 'a year, and company', 0.55, 0.64, 64, 'swim', art.orca),
]
