/**
 * Sea facts for the daily surprise, one line each, from docs/RESEARCH-SEA.md
 * (the sourced list). Contested or estimated claims from the research are
 * left out; the ones here are the plainly documented ones.
 */
export const SEA_FACTS: readonly string[] = [
  'in 2019 a milky sea glowed for weeks over an area the size of iceland.',
  'plankton flash when the water around them is stirred; a paddle is enough.',
  'sea sparkle is a rust-coloured tide by day and burns blue at night.',
  'flashlight fish blink by covering bacteria that never stop glowing.',
  'each spring, firefly squid turn the surface of toyama bay blue.',
  'a grabbed atolla jellyfish spins a wheel of light to summon a bigger predator.',
  'the largest glowing vertebrate is a shark nearly two metres long.',
  'the dragonfish hunts with a red light its prey cannot see.',
  'the vampire squid is not a squid, and it eats falling marine snow.',
  'a pyrosome is thousands of tiny animals sharing one glowing tube.',
  'the bloody-belly comb jelly is red because red is invisible in the deep.',
  'the barreleye looks out through its own transparent forehead.',
  'a siphonophore filmed off australia was about 45 metres long.',
  "the portuguese man o' war is not one animal but a colony under sail.",
  'the deepest octopus ever filmed was nearly seven kilometres down.',
  'a male anglerfish fuses to the female and shares her blood.',
  'yeti crabs farm bacteria on their hairy arms and wave them to feed the crop.',
  'hydrothermal vents were found in 1977; no one expected animals there.',
  'the lost city vents grow white limestone towers 60 metres tall.',
  'a dead whale on the seafloor can feed a community for decades.',
  'bone-eating worms have no mouth; their tiny males live inside the females.',
  'the twilight zone may hold more fish than the rest of the ocean combined.',
  'wartime sonar found a false seafloor that rose at dusk; it was fish.',
  'every night, about ten billion tonnes of animals rise toward the surface.',
  'the lanternfish may be the most common fish on earth; few have seen one.',
  'until 2019, only three people had reached the bottom of challenger deep.',
  'only about a quarter of the seafloor has been mapped in detail.',
  'the largest waterfall on earth is underwater, between iceland and greenland.',
  'a brinicle is a finger of ice that sinks and freezes what it touches.',
  'a giant larvacean builds a new mucus house every day and lets the old one sink.',
  'glass squid fill a chamber with ammonia so they can float without swimming.',
  'sea pigs walk the abyssal floor; young crabs hide underneath them.',
  'a giant isopod in a japanese aquarium went five years without eating.',
  'a deep-sea octopus guarded her eggs for four and a half years without eating.',
  'the first live colossal squid ever filmed was a 30 cm juvenile, in 2025.',
  'sea spiders keep their guts in their legs and use them to pump blood.',
  'antarctic icefish have no red blood cells; their blood runs clear.',
  'bacteria named after the titanic are slowly eating its hull.',
  'hagfish slime grows ten thousand times larger in under half a second.',
  'the oarfish is the longest bony fish; it does not predict earthquakes.',
  'a bobbit worm waits under the sand with jaws that can cut a fish in two.',
  'narwhal tusks carry about ten million nerve endings.',
  'sperm whales sleep upright, nose to the sky, for minutes at a time.',
  'a sperm whale click is the loudest sound any animal makes.',
  'sperm whale clans click in dialects that are learned, not inherited.',
  'new humpback songs spread eastward across the pacific, replacing the old.',
  'a lone humpback can tune the size and rings of its bubble net.',
  "a diving blue whale's heart can slow to two beats a minute.",
  'bowhead whales can pass 200 years; stone harpoon tips have turned up in them.',
  "a cuvier's beaked whale once held its breath for 222 minutes.",
  "whale earwax grows in layers and records the whale's whole life.",
  'dolphins sleep one half of the brain at a time, one eye open.',
  'whale shark spots are matched with software written for mapping stars.',
  'ming the clam lived 507 years and died when it was opened to be counted.',
  'the immortal jellyfish can grow backwards into a polyp and start again.',
  'mantis shrimp have up to sixteen kinds of colour receptor; people have three.',
  'octopuses change colour in their sleep, about once an hour.',
  'veined octopuses carry coconut halves to assemble into shelters later.',
  'an octopus has three hearts; one stops whenever it swims.',
  'a female blanket octopus can be forty thousand times heavier than her mate.',
  'some sea slugs eat anemones and store the stings in their own backs.',
  'a comet star regrows an entire body from a single arm.',
  'a sea cucumber can throw out its own organs and grow them back.',
  'the sea angel is a snail with no shell and wings instead of a foot.',
  'a moon jellyfish is about 95 percent water and has no brain.',
  'a 12 cm pufferfish spends a week carving a two-metre circle in the sand.',
  'great barrier reef corals spawn together a few nights after a full moon.',
  'sea otters wrap themselves in kelp so they do not drift off while asleep.',
  'the 52-hertz whale sings at a pitch no other known whale uses.',
]
