/**
 * Before 0.12 a thing wore an emoji. Moving to glyphs, the emoji it wore
 * says best what it meant, so it is read first, through this table; only
 * an emoji that is not here falls back to the name (match.ts), and a name
 * that fits nothing to a monogram. Covers the emoji the add sheet offered,
 * the starters, and the ones people reach for most for habits.
 */
const TABLE: Readonly<Record<string, string>> = {
  '🏃': 'run',
  '👟': 'run',
  '🚶': 'walk',
  '🥾': 'walk',
  '🏋': 'gym',
  '💪': 'pushups',
  '🤸': 'stretch',
  '🧘': 'meditate',
  '🚴': 'bike',
  '🚲': 'bike',
  '🏊': 'swim',
  '😴': 'sleep',
  '🛏': 'sleep',
  '🌙': 'sleep',
  '💧': 'water',
  '🥤': 'water',
  '💊': 'vitamins',
  '🥦': 'food',
  '🍎': 'food',
  '🥗': 'food',
  '🍏': 'food',
  '👣': 'steps',
  '📚': 'read',
  '📖': 'read',
  '🎓': 'study',
  '🧠': 'study',
  '✏': 'write',
  '✍': 'write',
  '📝': 'write',
  '🌬': 'breathe',
  '🗣': 'language',
  '🌍': 'language',
  '💻': 'code',
  '⌨': 'code',
  '📋': 'plan',
  '✅': 'plan',
  '🗓': 'plan',
  '📵': 'nophone',
  '📱': 'nophone',
  '📓': 'journal',
  '📔': 'journal',
  '🎻': 'violin',
  '🎸': 'guitar',
  '🎹': 'piano',
  '🎤': 'sing',
  '🎵': 'music',
  '🎶': 'music',
  '🥁': 'music',
  '🎺': 'music',
  '🎷': 'music',
  '🎨': 'draw',
  '🖌': 'draw',
  '📷': 'photo',
  '📸': 'photo',
  '🍳': 'cook',
  '🔨': 'build',
  '🛠': 'build',
  '🧶': 'build',
  '🎧': 'listen',
  '🧹': 'clean',
  '🧽': 'clean',
  '🌱': 'plants',
  '🪴': 'plants',
  '🌿': 'plants',
  '💰': 'save',
  '🐷': 'save',
  '☕': 'cup',
  '🍵': 'cup',
  '👕': 'laundry',
  '🧺': 'laundry',
  '📞': 'call',
  '☎': 'call',
  '👫': 'friend',
  '🤝': 'friend',
  '❤': 'kindness',
  '💛': 'kindness',
  '🙏': 'kindness',
  '🐕': 'dog',
  '🐶': 'dog',
  '🐈': 'dog',
  '✉': 'mail',
  '📧': 'mail',
  '🦷': 'teeth',
  '🪥': 'teeth',
  '🧴': 'skin',
  '🚿': 'shower',
  '🛁': 'shower',
  '🌳': 'outside',
  '🌲': 'outside',
  '🏞': 'outside',
  '☀': 'sun',
  '🌅': 'sun',
  '🌞': 'sun',
}

/**
 * The glyph an emoji meant, or undefined. Variation selectors, skin tones
 * and the rest of a joined sequence are dropped first: "🏃‍♀️" is "🏃".
 */
export function glyphForEmoji(emoji: string): string | undefined {
  const base = Array.from(emoji.replace(/️/g, ''))[0]
  return base === undefined ? undefined : TABLE[base]
}
